language: node_js
node_js:
  - lts/*

dist: trusty
sudo: false

deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master

script: bash scripts/deploy.sh

cache:
directories:
  - node_modules