language: node_js
node_js:
  - '13.7.0'

  cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master

before_install: 
  - yarn global add gatsby-cli

install: 
  - yarn build

script:
  - gatsby build --prefix-paths

dist: trusty
sudo: false